<?php

/**
 * CategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Categories');
    }
            	    public function func_getProductsByCategoryName($category_name)
    {
           return $q = Doctrine_Query::create()
                    ->select('c.*,p.*')
                    ->from('Categories c')
                    ->leftJoin('c.Products p')
                    ->where('c.name = ?', $category_name)
                    ->fetchArray();
    }
                	    public function func_getProductsByCategoryNameFeatured($category_name)
    {
           return $q = Doctrine_Query::create()
                    ->select('c.*,p.*')
                    ->from('Categories c')
                    ->leftJoin('c.Products p')
                    ->where('c.name = ?', $category_name)
                   ->andWhere('p.featured = ?',1)
                    ->fetchArray();
    }
}