<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MyDesign', 'doctrine');

/**
 * BaseMyDesign
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $my_design_id
 * @property integer $user_id
 * @property string $image
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property User $User
 * 
 * @method integer   getMyDesignId()   Returns the current record's "my_design_id" value
 * @method integer   getUserId()       Returns the current record's "user_id" value
 * @method string    getImage()        Returns the current record's "image" value
 * @method timestamp getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()    Returns the current record's "updated_at" value
 * @method User      getUser()         Returns the current record's "User" value
 * @method MyDesign  setMyDesignId()   Sets the current record's "my_design_id" value
 * @method MyDesign  setUserId()       Sets the current record's "user_id" value
 * @method MyDesign  setImage()        Sets the current record's "image" value
 * @method MyDesign  setCreatedAt()    Sets the current record's "created_at" value
 * @method MyDesign  setUpdatedAt()    Sets the current record's "updated_at" value
 * @method MyDesign  setUser()         Sets the current record's "User" value
 * 
 * @package    devil
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMyDesign extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('my_design');
        $this->hasColumn('my_design_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'user_id'));
    }
}