# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: user, action: login }
logout:
  url:     /logout
  param:   { module: user, action: logout }
login:
  url:   /
  param: { module: user, action: login }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:user
  param: { action: login }

default:
  url:   /:module/:action/*
