# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        PLP - Administrator Area
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css,jquery-ui-1.7.3.custom.css]

  javascripts:    [jquery-1.7.1.min.js,jquery.ui.datepicker.js,jquery.ui.core.js,registration.js]

  has_layout:     true
  layout:         layout
