<?php

/**
 * OrderSessionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderSessionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderSessionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderSessions');
    }
}