<?php

/**
 * OrdersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Orders');
    }
}