<?php

/**
 * ProductsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ProductsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Products');
    }

    public function func_getProductsByName($product_name) {
        return $q = Doctrine_Query::create()
                ->from('Products')
                ->where('name = ?', $product_name)
                ->fetchArray();
    }

    public function func_getProduct($product_id) {
        $q = $this->createQuery('u')
                ->where('u.product_id = ?  ', $product_id)
                ->fetchArray();
        return $q;
    }

}