<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('User');
    }

    public function func_checkLogin($post_values) {
        $q = $this->createQuery('u')
                ->where('u.email = ?  ', $post_values['users']['email'])
                ->andWhere('u.pass = ?', $post_values['users']['password'])
                ->fetchArray();
        return $q;
    }
        public function func_checkLoginBackend($post_values) {
        $q = $this->createQuery('u')
                ->where('u.email = ?  ', $post_values['email'])
                ->andWhere('u.pass = ?', $post_values['password'])
                ->fetchArray();
        return $q;
    }
    

    public function func_getUser($user_id) {
        $q = $this->createQuery('u')
                ->where('u.user_id = ?  ', $user_id)
                ->fetchArray();
        return $q;
    }
        public function func_getUserAndOrderId($user_id) {
        $q = $this->createQuery('u')
                ->leftJoin('u.Orders o')
                ->where('u.user_id = ?  ', $user_id)
                ->andWhere('order_sessions_id = ?', session_id())
                ->fetchArray();
        return $q;
    }

}