<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }
        public function func_checkLogin($post_values)
    {
                          $q = $this->createQuery('u')
                            ->where('u.email = ?  ', $post_values['users']['email'])
                            ->andWhere('u.pass = ?', $post_values['users']['password'])
                            ->fetchArray();
							return $q; 
    }
}