<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/08 04:44:29

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=devilsattitude',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
