<?php

/**
 * MyDesignTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MyDesignTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MyDesignTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MyDesign');
    }
}