<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/07/07 22:06:23
sfConfig::add(array(
  'app_globals_merchant_id' => 'M_dro19479_19479',
  'app_globals_working_key' => '4yasvbucx9hxdijlc7',
  'app_globals_redirect_url' => 'http://www.devilsattitude.com/order/thankyou',
));
