<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/07/07 22:06:23

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=devilsattitude',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
