<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/05/23 17:48:11
sfConfig::add(array(
  'app_globals_merchant_id' => 'M_dro19479_19479',
  'app_globals_working_key' => '4yasvbucx9hxdijlc7',
));
