<?php
// auto-generated by sfViewConfigHandler
// date: 2012/05/12 06:37:17
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('layout.css', '', array ());
  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('style-category.css', '', array ());
  $response->addJavascript('jquery-1.5.2.js', '', array ());
  $response->addJavascript('cufon-yui.js', '', array ());
  $response->addJavascript('cufon-replace.js', '', array ());
  $response->addJavascript('Terminal_Dosis_300.font.js', '', array ());
  $response->addJavascript('atooltip.jquery.js', '', array ());
  $response->addJavascript('roundabout.js', '', array ());
  $response->addJavascript('roundabout_shapes.js', '', array ());
  $response->addJavascript('jquery.easing.1.2.js', '', array ());
  $response->addJavascript('script.js', '', array ());
  $response->addJavascript('main.js', '', array ());
  $response->addJavascript('jquery.popup.js', '', array ());


